### ISSUE TITLE
syncthing没得zh-cn链接

### ISSUE THREAD

**Issue by rq1025330** [immortalwrt/luci#104]
![image](https://user-images.githubusercontent.com/52870887/144872705-aa4d71c1-c74e-47d6-8a82-c02d92639819.png)

**Comment by zxlhhyccc** [comment]
master分支为啥要zh-cn？？？？

**Comment by rq1025330** [comment]
> master分支为啥要zh-cn？？？？

编译出来没完全汉化 添加就可以

**Comment by zxlhhyccc** [comment]
> > master分支为啥要zh-cn？？？？
> 
> 编译出来没完全汉化 添加就可以

你的问题。。。。

**Comment by 1715173329** [comment]
please check `default-settings-chn`.

**Comment by rq1025330** [comment]
> please check `default-settings-chn`.
哦哦，
![image](https://user-images.githubusercontent.com/52870887/144882140-16b2b67b-14ac-4306-978e-dcde923206eb.png)
wo'zhe'yan我这样添加就可以 ，
![image](https://user-images.githubusercontent.com/52870887/144882365-7c1084ea-8e57-43c5-8fd4-85ddac79ea0a.png)

kenzok8也是这样改的 ，我是小白 才接触 ，提的问题比较低级 ，实在不好意思
