### ISSUE TITLE
luci-app-turboacc在master分支下启动dns缓存后再禁用，无法停止运行，必须重启机器才能停止

### ISSUE THREAD

**Issue by zxlhhyccc** [immortalwrt/luci#119]
![image](https://user-images.githubusercontent.com/45259624/148891670-78dce972-cc74-478f-9caa-003deca67fa1.png)

**Comment by AmadeusGhost** [comment]
![-660b164807496f89.jpg](https://user-images.githubusercontent.com/42570690/148978384-7446a2ad-7ecd-463c-a642-a022e1c5c19d.jpg)

**Comment by 1715173329** [comment]
seems that it works fine for me
