### ISSUE TITLE
TurboAcc里面的shortcut-fe是个好东西，可以加回来吗

### ISSUE THREAD

**Issue by jinlife** [immortalwrt/luci#196]
luci-app-turboacc

## Steps to reproduce:
参看 https://www.youtube.com/watch?v=ATTCCnTEqH0&ab_channel=%E6%B4%8B%E8%91%B1
里面做的测试，小包转发，Openwrt就靠Shortcut-FE了。Offloading貌似对小包没作用。

**Comment by jinlife** [comment]
master上没有，21.02分支有。

**Comment by 1715173329** [comment]
少看 youtuber 多学习。
