### ISSUE TITLE
Incorrect language

### ISSUE THREAD

**Issue by kyliezero** [immortalwrt/luci#199]
can you fix this, some packages with english not correct [luci-app-nextdns](https://github.com/immortalwrt/luci/blob/7a8e40dd1911593e8e36fd7781ec882752888810/applications/luci-app-nextdns/po/en/nextdns.po#L15) [luci-app-dnscrypt-proxy](https://github.com/immortalwrt/luci/blob/7a8e40dd1911593e8e36fd7781ec882752888810/applications/luci-app-dnscrypt-proxy/po/en/dnscrypt-proxy.po#L190) [luci-app-attendedsysupgrade](https://github.com/immortalwrt/luci/blob/7a8e40dd1911593e8e36fd7781ec882752888810/applications/luci-app-attendedsysupgrade/po/en/attendedsysupgrade.po#L160) and many others you can find yourself, thank you

**Comment by msylgj** [comment]
Upstream problem. via: https://github.com/openwrt/luci/commit/62ee3fbfbf91e41d1260ea7023145fbdd4eb0d86

Please report it in the upsteam repo. https://github.com/openwrt/luci/issues
