### ISSUE TITLE
openvpn client /luci Integration

### ISSUE THREAD

**Issue by evenlee** [immortalwrt/luci#211]
can we integrate openvpn client related luci app package？

**Comment by 1715173329** [comment]
idk what it is

**Comment by evenlee** [comment]
[openvpn-openssl](https://openwrt.org/packages/pkgdata/openvpn-openssl) and [luci-app-openvpn](https://openwrt.org/packages/pkgdata/luci-app-openvpn)

I want to use openvpn client in a router, thanks

**Comment by 1715173329** [comment]
it's upstreamed, so we have it too
idk what do u mean by "integrate", it's already available in our opkg feeds

**Comment by evenlee** [comment]
I am using [SuLingGG](https://github.com/SuLingGG) /[OpenWrt-Rpi](https://github.com/SuLingGG/OpenWrt-Rpi), which is based on immortalwrt and seems does not have openvpn client installed by default, thanks for confirming.
