### ISSUE TITLE
关于 luci-app-bitsrunlogin-go 的原维护仓库

### ISSUE THREAD

**Issue by Revincx** [immortalwrt/luci#214]
请问 [luci-app-bitsrunlogin-go](https://github.com/immortalwrt/luci/tree/master/applications/luci-app-bitsrunlogin-go) 这个包是在哪里维护的呢？
想提几个 Pull Request 却找不到原仓库在哪，还是说直接在这里提 pr 就可以呢？

**Comment by 1715173329** [comment]
在这里提交就好。

**Comment by Revincx** [comment]
> 在这里提交就好。

好的

**Comment by Revincx** [comment]
> 在这里提交就好。

再问一下，是提交到 master 分支上还是 21.02 分支上呢

**Comment by 1715173329** [comment]
如无分支特定更改，请优先提交到 master 分支。

**Comment by Revincx** [comment]
> 如无分支特定更改，请优先提交到 master 分支。

OK
