### ISSUE TITLE
ipv4 traceroute Error: XHR request timed out

### ISSUE THREAD

**Issue by zzz6839** [immortalwrt/luci#216]
firmware ver.
```
ImmortalWrt 21.02-SNAPSHOT r19612-f23a3e25ac / LuCI openwrt-21.02 branch git-22.270.33630-e4bcddb
```
The same behavior with [this issue](https://github.com/openwrt/luci/issues/5782), this problem has been fixed in this commit, (https://github.com/openwrt/luci/commit/1ae142d7d11862b11a6e0cea06562875cc778ae7), idk how to pull a request, pls consider to fix it, thank you

**Comment by 1715173329** [comment]
done in 2216cc6c7ef921b7f4fedaa7a04c60ec085a2b8a.
