### ISSUE TITLE
跟进适配smartdns 38.1 luci

### ISSUE THREAD

**Issue by SakuraFallingMad** [immortalwrt/luci#219]
如题，luci-app-smartdns 需要适配，目前的版本会重复提交重定向端口的问题，也许还有其他新功能的适配。还是希望同步适配luci。
![image](https://user-images.githubusercontent.com/31793080/198857608-631471d2-8d41-4ed7-949b-4c4b313a432e.png)

**Comment by ksong008** [comment]
@SakuraFallingMad 首先是什么分支，其次这问题不应该去smartdns反馈吗？

**Comment by SakuraFallingMad** [comment]
> @SakuraFallingMad 首先是什么分支，其次这问题不应该去smartdns反馈吗？

是这边immortalwrt里的luci本身需要更新了呀

**Comment by ksong008** [comment]
@SakuraFallingMad 就是smart那边更新了，我们这边没同步是吧

**Comment by 1715173329** [comment]
openwrt/luci 中的源码仍未更新。

**Comment by SakuraFallingMad** [comment]
那issue先留着吧，何时更新了再关吧
