### ISSUE TITLE
Passwall 编译不通过

### ISSUE THREAD

**Issue by Gzxhwq** [immortalwrt/luci#22]
/workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/luci-app-passwall.postinst-pkg: line 4: syntax error near unexpected token `)'
/workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/opkg/info/luci-app-passwall.postinst-pkg: line 4: `	(. /etc/uci-defaults/luci-passwall) && rm -f /etc/uci-defaults/luci-passwall)'
postinst script ./usr/lib/opkg/info/luci-app-passwall.postinst has failed with exit code 1
package/Makefile:66: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
package/Makefile:109: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2
Error: Process completed with exit code 2.

**Comment by asiaon123** [comment]
```
cp -fpR /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root.orig-ramips
/workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 5: /lib/functions.sh: No such file or directory
/workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/etc/init.d/arpbind: line 6: /lib/functions/network.sh: No such file or directory
/workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/info/luci-app-passwall.postinst-pkg: line 4: syntax error near unexpected token `)'
/workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/lib/opkg/info/luci-app-passwall.postinst-pkg: line 4: `	(. /etc/uci-defaults/luci-passwall) && rm -f /etc/uci-defaults/luci-passwall)'
postinst script ./usr/lib/opkg/info/luci-app-passwall.postinst has failed with exit code 1
make[2]: *** [package/install] Error 1
package/Makefile:66: recipe for target 'package/install' failed
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_install] Error 2
package/Makefile:109: recipe for target '/workdir/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_install' failed
make: *** [world] Error 2
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
Error: Process completed with exit code 2.
```
