### ISSUE TITLE
turboacc打开dns缓存再关闭不能上网

### ISSUE THREAD

**Issue by windybird** [immortalwrt/luci#220]
打开turboacc的DNS缓存时，DNS转发增加127.0.0.1:5333,关闭tuboacc的DNS缓存时，DNS转发127.0.0.1:5333不自动删除。。相关文件为openwrt/feeds/luci/applications/luci-app-turboacc/root/etc/init.d/turboacc的297、298行顺序造成。。当然还有其他修改方法。。。

**Comment by 1715173329** [comment]
this feature was removed.
