### ISSUE TITLE
Luci-app-turboacc not available for snapshot

### ISSUE THREAD

**Issue by naveen1hot** [immortalwrt/luci#223]
Hi immortal, request to kindly provide luci-app-turboacc version for snapshot version tooo.

**Comment by 1715173329** [comment]
Useless.

**Comment by naveen1hot** [comment]
Useless means I couldn't understand. It's just request I asked for the package. If not possible pls close as not available or something. Pls don't use useless word here.

**Comment by naveen1hot** [comment]
Oh. Thanks for the update buddy.
