### ISSUE TITLE
netdata编译了 没显示出来 用不了

### ISSUE THREAD

**Issue by yyhhkya** [immortalwrt/luci#236]
### Describe the bug

openwrt-21.02 分支

netdata 编译了 没显示出来 用不了
![image](https://user-images.githubusercontent.com/87574541/213722970-4897d53a-3142-4e6c-bf60-4b2490a779a3.png)

这是 .config
[https://github.com/yyhhkya/build-immortalwrt/blob/newifi3-d2--202301202058/.config](https://github.com/yyhhkya/build-immortalwrt/blob/newifi3-d2--202301202058/.config)

### ImmortalWrt version

r19866-5657d4ffb0

### ImmortalWrt target/subtarget

ramips/mt7621

### Device

Newifi-D2

### Image kind

Official downloaded image

### Terms

- [x] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by zcluo** [comment]
别编了一自己下一个安装下
if [ ! -f "/opt/netdata/bin/netdata" ];then
	mkdir -p /opt/netdata/etc/netdata
	cp -f /etc/netdata/*.conf /opt/netdata/etc/netdata/
##	cd /root/netdata-offline
##	chmod +x install.sh
    wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --prepare-offline-install-source  /tmp/netdata-offline
	cd /tmp/netdata-offline
	nohup ./install.sh --non-interactive &
else
	sleep 5
	[  -d "/tmp/netdata-offline/" ] && rm -rf /tmp/netdata-offline
	ps -ef | grep netdata | grep -v grep | awk {'print $1'} | xargs kill -9
	. /opt/netdata/bin/netdata -P /tmp/netdata.pid >> /tmp/netdata.out 2>&1 &
fi

**Comment by zcluo** [comment]
自己下一个安装。包里的版本太低了
`if [ ! -f "/opt/netdata/bin/netdata" ];then
	mkdir -p /opt/netdata/etc/netdata
	cp -f /etc/netdata/*.conf /opt/netdata/etc/netdata/
##	cd /root/netdata-offline
##	chmod +x install.sh
    wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --prepare-offline-install-source  /tmp/netdata-offline
	cd /tmp/netdata-offline
	nohup ./install.sh --non-interactive &
else
	sleep 5
	[  -d "/tmp/netdata-offline/" ] && rm -rf /tmp/netdata-offline
	ps -ef | grep netdata | grep -v grep | awk {'print $1'} | xargs kill -9
	. /opt/netdata/bin/netdata -P /tmp/netdata.pid >> /tmp/netdata.out 2>&1 &
fi`

**Comment by zcluo** [comment]
> if [ ! -f "/opt/netdata/bin/netdata" ];then
	mkdir -p /opt/netdata/etc/netdata
	cp -f /etc/netdata/*.conf /opt/netdata/etc/netdata/
##	cd /root/netdata-offline
##	chmod +x install.sh
    wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --prepare-offline-install-source  /tmp/netdata-offline
	cd /tmp/netdata-offline
	nohup ./install.sh --non-interactive &
else
	sleep 5
	[  -d "/tmp/netdata-offline/" ] && rm -rf /tmp/netdata-offline
	ps -ef | grep netdata | grep -v grep | awk {'print $1'} | xargs kill -9
	. /opt/netdata/bin/netdata -P /tmp/netdata.pid >> /tmp/netdata.out 2>&1 &
fi

**Comment by zcluo** [comment]
`if [ ! -f "/opt/netdata/bin/netdata" ];then
	mkdir -p /opt/netdata/etc/netdata
	cp -f /etc/netdata/*.conf /opt/netdata/etc/netdata/
    wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --prepare-offline-install-source  /tmp/netdata-offline
	cd /tmp/netdata-offline
	nohup ./install.sh --non-interactive &
else
	sleep 5
	[  -d "/tmp/netdata-offline/" ] && rm -rf /tmp/netdata-offline
	ps -ef | grep netdata | grep -v grep | awk {'print $1'} | xargs kill -9
	. /opt/netdata/bin/netdata -P /tmp/netdata.pid >> /tmp/netdata.out 2>&1 &
fi`

**Comment by 1715173329** [comment]
需要 netdata 处于运行状态才会显示。此外需要清理 luci 缓存。
