### ISSUE TITLE
Luci-app-msd_lite luci界面错误

### ISSUE THREAD

**Issue by CHDman** [immortalwrt/luci#283]
![image](https://user-images.githubusercontent.com/20582736/223578595-e8b3583a-650d-47ff-bf7e-b4ba7e2d88d0.png)

刚安装上去的时候可以正常打开，后面就不行了

**Comment by 1715173329** [comment]
https://github.com/immortalwrt/luci/commit/d9d4903d206b3ded1d2962d8abc124569dd867be
