### ISSUE TITLE
在 zerotier 的 LuCi 页面显示节点的地址信息

### ISSUE THREAD

**Issue by wingkinl** [immortalwrt/luci#324]
前阵子我在 ZeroTier 管理网站误删了一个节点，然后要恢复必须手动输入删除节点的地址添加回去，但是我没有记下那个地址，只好用了其他方法让家人 SSH 上去帮忙。如果 luci 上面可以直接显示当前地址就方便很多了（家人不需要操作SSH）。

**Comment by 1715173329** [comment]
需求过于小众且没有必要。
