### ISSUE TITLE
21.02分支luci-app-qibittorrent的”启用“开关无反应

### ISSUE THREAD

**Issue by science2468** [immortalwrt/luci#336]
# Issue template:
1. Please make sure that the issue subject starts with `<package-name>:`luci-app-qibittorrent
2. Issues related to end of life (EOL) releases are not supported or maintained and will be closed
3. Remove lines from top till here and fill in the following questions
***

## Steps to reproduce:
从软件包里面下载安装luci-app-qbittorrent后，在启用旁打✔后，点击”保存并应用“后，luci界面显示qibittorrent未运行，尝试多次结果是未运行。在启动项里面启动qbittorrent后，qbit的luci界面显示qbit已运行。

## Actual behavior:
qbittorrent的luci界面的”启用“开关没有反应，在启动项里，启动和停止可以控制qbittorrent。

**Comment by 1715173329** [comment]
需要手动重载 ucitrack 服务，或重启系统。
