### ISSUE TITLE
luci-app-unblockneteasemusic-go: WARNING: Makefile has a dependency on 'UnblockNeteaseMusic-Go', which does not exist

### ISSUE THREAD

**Issue by cherinyy** [immortalwrt/luci#345]
# Issue template:
1. Please make sure that the issue subject starts with `<package-name>:`
2. Issues related to end of life (EOL) releases are not supported or maintained and will be closed
3. Remove lines from top till here and fill in the following questions
***

## Steps to reproduce:

1. `git clone https://github.com/hanwckf/immortalwrt-mt798x.git`
2. `cd immortalwrt-mt798x && git pull && ./scripts/feeds update -a && ./scripts/feeds install -a`

## Actual behavior:

```
...
Updating feed 'luci' from 'https://github.com/immortalwrt/luci.git;openwrt-21.02' ...
已经是最新的。
Create index file './feeds/luci.index'
...
WARNING: Makefile 'package/feeds/luci/luci-app-unblockneteasemusic-go/Makefile' has a dependency on 'UnblockNeteaseMusic-Go', which does not exist
```

**Comment by 1715173329** [comment]
Dropped.
