### ISSUE TITLE
Attended Sysupgrade not working due to cloud flare block

### ISSUE THREAD

**Issue by naveen1hot** [immortalwrt/luci#367]
Hi Team,
Whenever I trying I getting blocked for the access.. request to kindly unblock/remove the cloudflare checking..  thanks in advance...

**Comment by soenggam** [comment]
@naveen1hot Could you disable your vpn ?

**Comment by naveen1hot** [comment]
Hello @soenggam , many thanks for your response.. I'm didn't using any VPN. I'm with the basic default settings.. but still I unable to access page.. even through mobile network I tried to access site.. but still getting error block..

**Comment by naveen1hot** [comment]
It's working now
