### ISSUE TITLE
NatMap 简体中文翻译有误

### ISSUE THREAD

**Issue by zzcabc** [immortalwrt/luci#368]
在master，2305分支中luci-app-natmap的一处简体中文翻译有误 后面的三个fff是多余的

https://github.com/immortalwrt/luci/blob/27ae250b64aa4d8b7548c9be6e424842074dfa7a/applications/luci-app-natmap/po/zh_Hans/natmap.po#L13-L15C12

**Comment by 1715173329** [comment]
去上游提交翻译即可。

**Comment by 1715173329** [comment]
Upstream fixed.
