### ISSUE TITLE
用的在线生成固件的方式.发现dhcp ,和raya,opkg configuration 

### ISSUE THREAD

**Issue by 142857X1** [immortalwrt/luci#439]
1.dhcp不晓得为什么有的有域名劫持 有的没有?当然咱的也没有..
(以前编译k2p的时候也没有这个选项,)而有的会有..咋会事?

这个已经找到了.原来是常规设置  地址

2.安装了raya  没有出现在服务选项里.重启也没有

3.opkg configuration  在/etc/opkg/customfeeds.conf项里添加 https://downloads.immortalwrt.org/releases/23.05.1/packages/aarch64_cortex-a53/luci/

然后安装任何一个包 都报错.
Errors
Collected errors:
 * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `https://downloads.immortalwrt.org/releases/23.05.1/packages/aarch64_cortex-a53/luci/'
不知道这样用是否是对的.如果是对的.如果您愿意请告知
如果这样用是不正确的.如果您愿意请告知正确的方式.

(关于语言包.要是能在选中的查下有附带语言包,能自动安装就更美了) 

# Issue template:
1. Please make sure that the issue subject starts with `<package-name>:`
2. Issues related to end of life (EOL) releases are not supported or maintained and will be closed
3. Remove lines from top till here and fill in the following questions
***

## Steps to reproduce:
**Example: Replace the following lines and remove this**

1. go to: Network → Interfaces → LAN (an interface with a static address) → DHCP server tab → IPv6 RA settings tab
2. set RA MTU and RA Hop Limit to arbitrary non-default value
3. Save & Apply
4. go to: IPv6 RA settings tab again

## Actual behavior:
**Example: Replace the following lines and remove this**

1. option ra_mtu '1500' is set correctly in /etc/config/dhcp
2. In LuCI though, RA MTU and RA Hop Limit are still displaying the default values in light gray font color.

## Expected behavior:
**Example: Replace the following lines and remove this**

```
RA MTU and RA Hop Limit are displaying the correct values found in /etc/config/dhcp in black font color.
```

## Additional Information:
OpenWrt version information from system `/etc/openwrt_release`

**Example: Replace the following lines and remove this**
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.0-rc4'
DISTRIB_REVISION='r16256-2d5ee43dc6'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 21.02.0-rc4 r16256-2d5ee43dc6'
DISTRIB_TAINTS=''
```

**Comment by 1715173329** [comment]
不需要你修改任何 opkg 配置。
