### ISSUE TITLE
luci ui显示内存占用和命令行中htop/free不一致

### ISSUE THREAD

**Issue by GeekSquirrel** [immortalwrt/luci#455]
Luci显示占用70%
![Screenshot_2024-10-23-19-16-40-415_Edge.jpg](https://github.com/user-attachments/assets/82075aee-6fa7-4ca3-81f6-7d4c310f4949)

htop和free都是占用50%左右

![Screenshot_2024-10-23-19-17-01-279_Termux.jpg](https://github.com/user-attachments/assets/a9c7297a-da94-4b6e-8e8b-b9ebc0142aad)

![Screenshot_2024-10-23-19-17-16-899_Termux.jpg](https://github.com/user-attachments/assets/530bad23-78ad-4d6b-802e-5624d1e062d5)

今天刚从openwrt迁过来，不太熟悉immortalwrt。这种情况正常吗？

**Comment by 1715173329** [comment]
显示内容更具体而已。openwrt 自 21.02 以来就用这种显示方式。

**Comment by GeekSquirrel** [comment]
> 刷新间隔时间不一样吧

不是，我刚才用cat /proc/meminfo看了下，也显示70%，Luci貌似就是引用的这个数据。

现在这个数据稳定地比htop的数据大10%-20%，之前在openwrt没发现有这个现象。

**Comment by 1715173329** [comment]
减去 buffer 和 cached 就一样了。

**Comment by GeekSquirrel** [comment]
> 显示内容更具体而已。openwrt 自 21.02 以来就用这种显示方式。

都是内存占用百分比，数值怎么会稳定相差10%-20%，我之前用的openwrt23.05也没发现有这个问题啊。
