### ISSUE TITLE
官方X86固件，安装passwall后luci-app-adblock不能去广告

### ISSUE THREAD

**Issue by sclsyin** [immortalwrt/luci#474]
### Describe the bug

官方X86固件，安装passwall后luci-app-adblock不能去广告

### ImmortalWrt version

r28061-399f9a1db3

### ImmortalWrt release

23.05.4

### ImmortalWrt target/subtarget

x86/64

### Device

QEMU Standard PC (Q35 + ICH9, 2009)

### Image kind

Official downloaded image

### Steps to reproduce

安装passwall后adblock广告拦截不能去广告

### Actual behaviour

adblock广告拦截不能去广告

### Expected behaviour

能去广告

### Additional info

![image](https://github.com/user-attachments/assets/ae931f3e-f842-4954-83bf-265c28e78945)
![image](https://github.com/user-attachments/assets/fbf8b3cb-e45a-41dd-a5ae-38821cb3fd7e)

### Terms

- [X] I am reporting an issue for ImmortalWrt, not an unsupported fork.

**Comment by 1715173329** [comment]
说明这两个插件有冲突，只能开一个。

**Comment by sclsyin** [comment]
> 说明这两个插件有冲突，只能开一个。

刚刚全新导入，只安装Adblock也不能过滤。。。
![image](https://github.com/user-attachments/assets/7226ddae-5ade-4811-85be-76697a522c21)
![image](https://github.com/user-attachments/assets/ea7220ed-ea2f-4215-ba75-71eb0a4b4ea1)
![image](https://github.com/user-attachments/assets/b6ba4cca-0ab8-4eb8-be37-d2be0e1fe428)

**Comment by 1715173329** [comment]
你指望 DNS 去广告能有什么效果，要有效果用浏览器插件和客户端。

**Comment by sclsyin** [comment]
额，之前旧版本的效果还是不错的呀。
