### ISSUE TITLE
[建议]增加 gowedav 多方案配置

### ISSUE THREAD

**Issue by imoldchen** [immortalwrt/luci#63]
webdav 目前只能配置一个共享方案, 之前用的 caddy+webdav 的方式, 可以配置一个端口下多用户并对应不同的目录, 因为路由器挂载了两个硬盘,作为私有云盘, 分别两人使用, 看到 gowebdav 已经有配置界面了, 希望配置界面能实现添加多个方案的功能.

**Comment by ElonH** [comment]
@1715173329 
有人实现了一个简单的luci

https://github.com/coolsnowwolf/luci/pull/158
https://github.com/coolsnowwolf/packages/pull/503/files

**Comment by 1715173329** [comment]
这。。该怎么说呢，确实是简单过头了

**Comment by 1715173329** [comment]
hacdias/webdav 支持 json 配置，要做一个 luci / uci 配置并不难，但是该项目貌似未给出具体配置说明

**Comment by 1715173329** [comment]
可以用 dufs。
