### ISSUE TITLE
是否可以考虑添加luci-app-dnsfilter插件

### ISSUE THREAD

**Issue by zhq1** [immortalwrt/luci#77]
https://github.com/kiddin9/luci-app-dnsfilter我自己编译进去使用感觉良好，就是有些域名误拦截了需要加白名单

**Comment by nicholas-opensource** [comment]
推荐使用原作者small-5的[luci-app-adblock-plus](https://github.com/small-5/luci-app-adblock-plus)

**Comment by zhq1** [comment]
原来这个就是哦，主要是我用过别人发的固件包里面这个，就以为那个就是他的  那我用这个，谢谢

**Comment by zhq1** [comment]
搞定了
