### ISSUE TITLE
[18.06-K5.4]无法启动docker daemon

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [immortalwrt/luci#80]
问题描述
luci-app-dockerman无法启动，提示：Please input the SOCKET PATH of docker daemon!

主机名 | ImmortalWrt
型号 | Raspberry Pi 4 Model B Rev 1.1
架构 | ARMv8 Processor rev 3 (v8l) x 4 (1500Mhz, 40.4°C)
固件版本 | ImmortalWrt 18.06-SNAPSHOT r10862-6b3a9d3a3 / LuCI openwrt-18.06-k5.4 branch (git-21.256.04965-a0664ec)
内核版本 | 5.10.64

![image](https://user-images.githubusercontent.com/38343280/133732163-5acd17d6-894f-4c3e-9dcf-cf58c7b9a45b.png)
![image](https://user-images.githubusercontent.com/38343280/133732213-fbfdcb0a-c998-411d-b2a7-172eef6e7460.png)

**Comment by 1715173329** [comment]
I don't use docker on openwrt, can you take a look?
Ping: @EnnawYang @SuLingGG

**Comment by EnnawYang** [comment]
上游的dockerman其实已经解决了不能启动的问题，但我试过bridge还是不通的，不知道是哪里的问题（

**Comment by 1715173329** [comment]
updated.

**Comment by ShoukakuChuuCC** [comment]
更新后还是无法启动docker daemon
![image](https://user-images.githubusercontent.com/38343280/134434886-57eb26ee-01b9-48c2-bef9-cc003ee06a1c.png)
![image](https://user-images.githubusercontent.com/38343280/134434905-dc983492-09a5-4a4f-ae9a-cd79a284318a.png)

**Comment by ShoukakuChuuCC** [comment]
配置页面直接一点信息都没有了

**Comment by 1715173329** [comment]
This issue should be addressed.
@ShoukakuChuuCC Can you make a test?

**Comment by ShoukakuChuuCC** [comment]
经验证，已修复，感谢大佬
