### ISSUE TITLE
luci-app-qbittorrent的qbittorrent能不再加个原版

### ISSUE THREAD

**Issue by hong0980** [immortalwrt/luci#88]
在用pt时用qBittorrent-Enhanced-Edition怕被封，在luci-app-qbittorrent中再加个原版的qbittorrent选择，谢谢！

**Comment by 1715173329** [comment]
fyi https://github.com/immortalwrt/packages/blob/master/net/qBittorrent-Enhanced-Edition/patches/100-use-original-user-agent.patch
