### ISSUE TITLE
luci-app-n2n_v2在master分支下不能启动！

### ISSUE THREAD

**Issue by zxlhhyccc** [immortalwrt/luci#97]
![image](https://user-images.githubusercontent.com/45259624/141052935-9796456d-aed1-4d62-8ebd-088014996569.png)

**Comment by AmadeusGhost** [comment]
Any error log?

**Comment by 1715173329** [comment]
tbh It's the magic of LuCI... It works if you call service file from ssh directly.

**Comment by zxlhhyccc** [comment]
> Any error log?

无日志，找不到luci哪里的问题，天灵说init可以启动，这个情况下那就是luci问题。。。

**Comment by zxlhhyccc** [comment]
> tbh It's the magic of LuCI... It works if you call service file from ssh directly.

经测试，不能运行是二进制问题，后使用大屌的n2n_v2编译包编译的二进制能正常运行，请天灵修复。。。。

**Comment by AmadeusGhost** [comment]
要修的话顺便问句，这玩意要升 2.9 吗

**Comment by 1715173329** [comment]
> 要修的话顺便问句，这玩意要升 2.9 吗

应该说是 [3.0](https://github.com/ntop/n2n/releases/tag/3.0)？
我没有用过，不清楚是否有破坏性更新。

**Comment by zxlhhyccc** [comment]
> 要修的话顺便问句，这玩意要升 2.9 吗

有必要更新到3.0，但目前配套的luci无法启动3.0版本。。。
