### ISSUE TITLE
luci-app-adguardhome代码已经不更新了，找到个新的，是否可替换？

### ISSUE THREAD

**Issue by dunkeng** [immortalwrt/luci#98]
https://github.com/rufengsuixing/luci-app-adguardhome
这个应该是不维护了，快两年没更新了，找到一个在更新能正常使用的
https://github.com/kenzok8/openwrt-packages/tree/master/adguardhome
https://github.com/kenzok8/openwrt-packages/tree/master/luci-app-adguardhome

**Comment by 1715173329** [comment]
imho 链接所指的 repo 真的没有什么说得上是“更新”的地方。
AdGuardHome 是自带 WebUI 的，为什么还要再去做一个这所谓“复杂的” LuCI 插件？
我找不到任何意义。
